// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ListItem from "./ListItem.bs.js";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";

import './HistoryList.css';
;

function HistoryList(Props) {
  var expenses = Props.expenses;
  var onRemoveItem = Props.onRemoveItem;
  return React.createElement("ul", {
              className: "list"
            }, Belt_Array.map(expenses, (function (expense) {
                    return React.createElement(ListItem.make, {
                                amount: expense.amount,
                                title: expense.title,
                                id: expense.id,
                                onRemoveItem: onRemoveItem
                              });
                  })));
}

var make = HistoryList;

export {
  make ,
}
/*  Not a pure module */
