// Generated by ReScript, PLEASE EDIT WITH CARE


var intial = {
  title: "",
  amount: "",
  titleState: false,
  amountState: false,
  amountTouched: false,
  titleTouched: false
};

export {
  intial ,
}
/* No side effect */
