// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";

import './LoginPage.css';
;

var initialState = {
  username: "",
  password: ""
};

function LoginPage(Props) {
  var handleLogin = Props.handleLogin;
  var loginState = Props.loginState;
  var match = React.useState(function () {
        return initialState;
      });
  var setInputState = match[1];
  var inputState = match[0];
  var match$1 = React.useState(function () {
        return false;
      });
  var setSubmitState = match$1[1];
  var usernameChangeHandler = function ($$event) {
    Curry._1(setInputState, (function (prev) {
            return {
                    username: $$event.target.value,
                    password: prev.password
                  };
          }));
  };
  var passwordChangeHandler = function ($$event) {
    Curry._1(setInputState, (function (prev) {
            return {
                    username: prev.username,
                    password: $$event.target.value
                  };
          }));
  };
  var loginSubmitHandler = function ($$event) {
    $$event.preventDefault();
    Curry._1(setSubmitState, (function (param) {
            return true;
          }));
    Curry._1(handleLogin, inputState);
  };
  return React.createElement("form", {
              className: "login-form",
              onSubmit: loginSubmitHandler
            }, React.createElement("div", {
                  className: "form_controls"
                }, React.createElement("label", {
                      htmlFor: "username"
                    }, "username"), React.createElement("input", {
                      id: "username",
                      type: "text",
                      onChange: usernameChangeHandler
                    })), React.createElement("div", {
                  className: "form_controls"
                }, React.createElement("label", {
                      htmlFor: "password"
                    }, "password"), React.createElement("input", {
                      id: "password",
                      placeholder: "password",
                      type: "password",
                      onChange: passwordChangeHandler
                    })), !loginState && match$1[0] ? React.createElement("p", {
                    className: "warning-text"
                  }, "Please Enter correct username or password") : null, React.createElement("button", undefined, "Login"));
}

var make = LoginPage;

export {
  initialState ,
  make ,
}
/*  Not a pure module */
