// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Converter from "../UI/Converter.bs.js";

import './DetailWidget.css';
;

function DetailWidget(Props) {
  var subtotals = Props.subtotals;
  console.log(subtotals.income);
  return React.createElement("div", {
              className: "display"
            }, React.createElement("div", undefined, React.createElement("p", undefined, "INCOME"), React.createElement("p", {
                      className: "income"
                    }, React.createElement(Converter.make, {
                          amount: subtotals.income
                        }))), React.createElement("div", undefined, React.createElement("p", undefined, "EXPENSE"), React.createElement("p", {
                      className: "expense"
                    }, React.createElement(Converter.make, {
                          amount: subtotals.expense
                        }))));
}

var make = DetailWidget;

export {
  make ,
}
/*  Not a pure module */
