// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Converter from "../UI/Converter.bs.js";
import * as DetailWidget from "./DetailWidget.bs.js";

import './Header.css';
;

function Header(Props) {
  var subtotal = Props.subtotal;
  var total = subtotal.income + subtotal.expense;
  return React.createElement("div", {
              className: "header"
            }, React.createElement("h3", undefined, "Expense Tracker"), React.createElement("p", {
                  className: "header-para"
                }, "Balance"), React.createElement("p", {
                  className: "header-amount"
                }, React.createElement(Converter.make, {
                      amount: total
                    })), React.createElement(DetailWidget.make, {
                  subtotals: subtotal
                }));
}

var make = Header;

export {
  make ,
}
/*  Not a pure module */
