// Generated by ReScript, PLEASE EDIT WITH CARE


var dtwHeading1 = "INCOME";

var dtwHeading2 = "EXPENSE";

var headerHeading = "Expense Tracker";

var headerText = "Balance";

var historyCardHeading = "History";

var inputFormLabel2 = "Amount";

var inputFormLabel1 = "Remark";

var inputFOrmPH1 = "Please Enter Remarks";

var inputFOrmPH2 = "Please Enter Amount";

var inputFormInfo = "Please enter with a negative sign for expenses";

var incomeItemStyle = "item green";

export {
  dtwHeading1 ,
  dtwHeading2 ,
  headerHeading ,
  headerText ,
  historyCardHeading ,
  inputFormLabel2 ,
  inputFormLabel1 ,
  inputFOrmPH1 ,
  inputFOrmPH2 ,
  inputFormInfo ,
  incomeItemStyle ,
}
/* No side effect */
