// Generated by ReScript, PLEASE EDIT WITH CARE


function calculate_Subtotal(expenses, str) {
  var check_Income_Expense = function (expense) {
    if (str === "income") {
      return expense.amount > 0.0;
    } else {
      return expense.amount < 0.0;
    }
  };
  return expenses.reduce((function (sum, expense) {
                if (check_Income_Expense(expense)) {
                  return expense.amount + sum;
                } else {
                  return sum;
                }
              }), 0.0);
}

var initialSubTotals = {
  income: 0.0,
  expense: 0.0
};

export {
  calculate_Subtotal ,
  initialSubTotals ,
}
/* No side effect */
