// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Types(Props) {
  var amount = Props.amount;
  return React.createElement("span", undefined, amount > 0.0 ? "$" + String(amount) + "" : "-$" + String(Math.abs(amount)) + "");
}

var make = Types;

export {
  make ,
}
/* react Not a pure module */
