// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Converter(Props) {
  var amount = Props.amount;
  var rPosAmnt = function (amount) {
    return "$" + amount.toFixed(2) + "";
  };
  var rNegAmnt = function (amount) {
    return "-$" + Math.abs(amount).toFixed(2) + "";
  };
  return React.createElement("span", undefined, amount >= 0.0 ? rPosAmnt(amount) : rNegAmnt(amount));
}

var make = Converter;

export {
  make ,
}
/* react Not a pure module */
