// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Converter(Props) {
  var amount = Props.amount;
  return React.createElement("span", undefined, amount >= 0.0 ? "$" + amount.toFixed(2) + "" : "-$" + Math.abs(amount).toFixed(2) + "");
}

var make = Converter;

export {
  make ,
}
/* react Not a pure module */
